In [1]:
%%capture

#Instalando o tweepy
!pip install tweepy

In [2]:
import tweepy
import math
import os.path
import pandas as pd
import json
from random import shuffle
import matplotlib.pyplot as plt
import numpy as np
import os

In [3]:
dados =pd.read_csv('databasePJF.csv', header=0, sep=',', quotechar='"')

In [4]:
dados

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.00,0.00,0,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.00,0.00,0,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.00,0.00,0,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.00,0.00,0,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.00,40348.79,0,0
10,1,DEBIT,9644.94,C1900366749,4465.00,0.00,C997608398,10845.00,157982.12,0,0
11,1,PAYMENT,3099.97,C249177573,20771.00,17671.03,M2096539129,0.00,0.00,0,0
12,1,PAYMENT,2560.74,C1648232591,5070.00,2509.26,M972865270,0.00,0.00,0,0
13,1,PAYMENT,11633.76,C1716932897,10127.00,0.00,M801569151,0.00,0.00,0,0
14,1,PAYMENT,4098.78,C1026483832,503264.00,499165.22,M1635378213,0.00,0.00,0,0
15,1,CASH_OUT,229133.94,C905080434,15325.00,0.00,C476402209,5083.00,51513.44,0,0
16,1,PAYMENT,1563.82,C761750706,450.00,0.00,M1731217984,0.00,0.00,0,0
17,1,PAYMENT,1157.86,C1237762639,21156.00,19998.14,M1877062907,0.00,0.00,0,0
18,1,PAYMENT,671.64,C2033524545,15123.00,14451.36,M473053293,0.00,0.00,0,0
19,1,TRANSFER,215310.30,C1670993182,705.00,0.00,C1100439041,22425.00,0.00,0,0
20,1,PAYMENT,1373.43,C20804602,13854.00,12480.57,M1344519051,0.00,0.00,0,0
21,1,DEBIT,9302.79,C1566511282,11299.00,1996.21,C1973538135,29832.00,16896.70,0,0
22,1,DEBIT,1065.41,C1959239586,1817.00,751.59,C515132998,10330.00,0.00,0,0
23,1,PAYMENT,3876.41,C504336483,67852.00,63975.59,M1404932042,0.00,0.00,0,0
24,1,TRANSFER,311685.89,C1984094095,10835.00,0.00,C932583850,6267.00,2719172.89,0,0
25,1,PAYMENT,6061.13,C1043358826,443.00,0.00,M1558079303,0.00,0.00,0,0
26,1,PAYMENT,9478.39,C1671590089,116494.00,107015.61,M58488213,0.00,0.00,0,0
27,1,PAYMENT,8009.09,C1053967012,10968.00,2958.91,M295304806,0.00,0.00,0,0
28,1,PAYMENT,8901.99,C1632497828,2958.91,0.00,M33419717,0.00,0.00,0,0
29,1,PAYMENT,9920.52,C764826684,0.00,0.00,M1940055334,0.00,0.00,0,0
...,...,...,...,...,...,...,...,...,...,...,...
6362590,741,TRANSFER,323726.61,C509686434,323726.61,0.00,C1310143791,0.00,0.00,1,0
6362591,741,CASH_OUT,323726.61,C919525792,323726.61,0.00,C993635374,561753.58,885480.19,1,0
6362592,741,TRANSFER,383661.10,C457476945,383661.10,0.00,C1688658215,0.00,0.00,1,0
6362593,741,CASH_OUT,383661.10,C369315575,383661.10,0.00,C2069429837,1788112.70,2171773.80,1,0
6362594,741,TRANSFER,144945.34,C31496887,144945.34,0.00,C1251365829,0.00,0.00,1,0
6362595,741,CASH_OUT,144945.34,C1092829426,144945.34,0.00,C716019997,0.00,144945.34,1,0
6362596,741,TRANSFER,48442.88,C1112979339,48442.88,0.00,C2114078084,0.00,0.00,1,0
6362597,741,CASH_OUT,48442.88,C1706094385,48442.88,0.00,C2109905271,513746.19,562189.07,1,0
6362598,742,TRANSFER,4009058.39,C1044665079,4009058.39,0.00,C750074708,0.00,0.00,1,0
6362599,742,CASH_OUT,4009058.39,C1970706589,4009058.39,0.00,C637394241,1229761.96,5238820.34,1,0
6362600,742,TRANSFER,652993.91,C40604503,652993.91,0.00,C1166857907,0.00,0.00,1,0
6362601,742,CASH_OUT,652993.91,C1614818636,652993.91,0.00,C362803701,0.00,652993.91,1,0
6362602,742,TRANSFER,1819543.69,C2089752665,1819543.69,0.00,C112833674,0.00,0.00,1,0
6362603,742,CASH_OUT,1819543.69,C1039979813,1819543.69,0.00,C2078394828,0.00,1819543.69,1,0
6362604,742,TRANSFER,54652.46,C1674778854,54652.46,0.00,C1930074465,0.00,0.00,1,0
6362605,742,CASH_OUT,54652.46,C43545501,54652.46,0.00,C830041824,0.00,54652.46,1,0
6362606,742,TRANSFER,303846.74,C959102961,303846.74,0.00,C114421319,0.00,0.00,1,0
6362607,742,CASH_OUT,303846.74,C1148860488,303846.74,0.00,C846260566,343660.89,647507.63,1,0
6362608,742,TRANSFER,258355.42,C1226129332,258355.42,0.00,C1744173808,0.00,0.00,1,0
6362609,742,CASH_OUT,258355.42,C1113162093,258355.42,0.00,C797688696,25176.67,283532.09,1,0
6362610,742,TRANSFER,63416.99,C778071008,63416.99,0.00,C1812552860,0.00,0.00,1,0
6362611,742,CASH_OUT,63416.99,C994950684,63416.99,0.00,C1662241365,276433.18,339850.17,1,0
6362612,743,TRANSFER,1258818.82,C1531301470,1258818.82,0.00,C1470998563,0.00,0.00,1,0
6362613,743,CASH_OUT,1258818.82,C1436118706,1258818.82,0.00,C1240760502,503464.50,1762283.33,1,0
6362614,743,TRANSFER,339682.13,C2013999242,339682.13,0.00,C1850423904,0.00,0.00,1,0
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.00,C776919290,0.00,339682.13,1,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.00,C1881841831,0.00,0.00,1,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.00,C1365125890,68488.84,6379898.11,1,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.00,C2080388513,0.00,0.00,1,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.00,C873221189,6510099.11,7360101.63,1,0

In [52]:
#criando um dataframe com menos não fraudes para tornar maior a proporção de fraudes para não fraudes.
dadosfraud = dados[(dados.isFraud == 1)]
dadosnfraud = dados[(dados.isFraud == 0)]
dadosnfraud = dadosnfraud.sample(frac = 1)
dadosnfraud = dadosnfraud.iloc[0:25000]
dadosfinais = pd.concat([dadosfraud,dadosnfraud])
dadosfinais

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1,0
251,1,TRANSFER,2806.00,C1420196421,2806.00,0.00,C972765878,0.00,0.00,1,0
252,1,CASH_OUT,2806.00,C2101527076,2806.00,0.00,C1007251739,26202.00,0.00,1,0
680,1,TRANSFER,20128.00,C137533655,20128.00,0.00,C1848415041,0.00,0.00,1,0
681,1,CASH_OUT,20128.00,C1118430673,20128.00,0.00,C339924917,6268.00,12145.85,1,0
724,1,CASH_OUT,416001.33,C749981943,0.00,0.00,C667346055,102.00,9291619.62,1,0
969,1,TRANSFER,1277212.77,C1334405552,1277212.77,0.00,C431687661,0.00,0.00,1,0
970,1,CASH_OUT,1277212.77,C467632528,1277212.77,0.00,C716083600,0.00,2444985.19,1,0
1115,1,TRANSFER,35063.63,C1364127192,35063.63,0.00,C1136419747,0.00,0.00,1,0
1116,1,CASH_OUT,35063.63,C1635772897,35063.63,0.00,C1983025922,31140.00,7550.03,1,0
1869,1,TRANSFER,25071.46,C669700766,25071.46,0.00,C1384210339,0.00,0.00,1,0
1870,1,CASH_OUT,25071.46,C1275464847,25071.46,0.00,C1364913072,9083.76,34155.22,1,0
1911,1,CASH_OUT,132842.64,C13692003,4499.08,0.00,C297927961,0.00,132842.64,1,0
2301,1,TRANSFER,235238.66,C1872047468,235238.66,0.00,C116289363,0.00,0.00,1,0
2302,1,CASH_OUT,235238.66,C1499825229,235238.66,0.00,C2100440237,0.00,235238.66,1,0
3059,2,TRANSFER,1096187.24,C1093223281,1096187.24,0.00,C2063275841,0.00,0.00,1,0
3060,2,CASH_OUT,1096187.24,C77163673,1096187.24,0.00,C644345897,0.00,1096187.24,1,0
3162,2,TRANSFER,963532.14,C1440057381,963532.14,0.00,C268086000,0.00,0.00,1,0
3163,2,CASH_OUT,963532.14,C430329518,963532.14,0.00,C991505714,132382.57,1095914.71,1,0
3271,2,TRANSFER,14949.84,C140702728,14949.84,0.00,C634210724,0.00,0.00,1,0
3272,2,CASH_OUT,14949.84,C395257482,14949.84,0.00,C1032986144,18161.79,33111.63,1,0
3683,2,TRANSFER,18627.02,C1375503918,18627.02,0.00,C234430897,0.00,0.00,1,0
3684,2,CASH_OUT,18627.02,C175961135,18627.02,0.00,C1711105800,147251.58,165878.60,1,0
4103,3,TRANSFER,10539.37,C1134864869,10539.37,0.00,C118648358,0.00,0.00,1,0
4104,3,CASH_OUT,10539.37,C1984954272,10539.37,0.00,C124540047,0.00,10539.37,1,0
4260,3,TRANSFER,22877.00,C1247938090,22877.00,0.00,C1002031672,0.00,0.00,1,0
4261,3,CASH_OUT,22877.00,C2126545173,22877.00,0.00,C573200870,0.00,22877.00,1,0
4440,4,TRANSFER,10000000.00,C7162498,12930418.44,2930418.44,C945327594,0.00,0.00,1,0
4441,4,CASH_OUT,10000000.00,C351297720,10000000.00,0.00,C766681183,0.00,9941904.21,1,0
...,...,...,...,...,...,...,...,...,...,...,...
5750034,399,PAYMENT,44387.66,C823230997,14089.38,0.00,M482773742,0.00,0.00,0,0
5814287,401,CASH_IN,255593.87,C511027703,2994639.23,3250233.09,C769484067,278640.57,23046.71,0,0
6034407,476,PAYMENT,10605.77,C1507581271,0.00,0.00,M484410837,0.00,0.00,0,0
6279772,644,PAYMENT,4779.22,C1376952230,0.00,0.00,M609247240,0.00,0.00,0,0
3115523,236,PAYMENT,20195.88,C459793958,30921.00,10725.12,M1132097560,0.00,0.00,0,0
4896937,349,CASH_IN,376618.16,C1516151305,2472042.74,2848660.90,C1634844699,1295931.78,919313.62,0,0
772957,39,CASH_IN,123916.75,C1804721245,20863065.96,20986982.71,C169406658,1049076.66,925159.91,0,0
3030683,233,PAYMENT,5935.09,C987627082,0.00,0.00,M1915232308,0.00,0.00,0,0
1528333,153,PAYMENT,4203.27,C1506339115,0.00,0.00,M455399542,0.00,0.00,0,0
4277099,307,PAYMENT,779.66,C1780545810,0.00,0.00,M985473151,0.00,0.00,0,0
1750781,161,CASH_OUT,124222.23,C1388765479,0.00,0.00,C1472216567,539095.43,663317.67,0,0
3138078,236,CASH_IN,292662.43,C861318912,42123.00,334785.43,C1413523806,2786041.50,2493379.07,0,0
1850955,164,PAYMENT,7773.40,C1279066584,197227.23,189453.83,M234530711,0.00,0.00,0,0
475752,19,TRANSFER,858777.22,C1293332541,0.00,0.00,C911407842,1374173.86,2081293.70,0,0
4461460,323,CASH_IN,177836.91,C1587901009,4174975.28,4352812.20,C2035699607,444312.73,266475.82,0,0
2100326,182,CASH_OUT,143234.63,C61711205,5652.00,0.00,C543752970,230147.43,373382.06,0,0
4389682,321,PAYMENT,15804.00,C1937990415,370174.00,354370.00,M412677419,0.00,0.00,0,0
6115298,527,PAYMENT,7324.51,C1196806318,62221.04,54896.53,M1905353621,0.00,0.00,0,0
5703364,398,CASH_OUT,4366.26,C344432145,51835.00,47468.74,C2001412536,0.00,4366.26,0,0
1065233,119,PAYMENT,4284.83,C1873909827,11301.00,7016.17,M942697660,0.00,0.00,0,0
106066,10,CASH_OUT,91942.04,C260063885,3182965.82,3091023.78,C910260446,1294305.21,1475274.89,0,0
2155019,184,CASH_OUT,149033.29,C482689420,448905.00,299871.71,C1954858043,22141.77,171175.05,0,0
3376322,254,CASH_OUT,215697.75,C1058898604,36648.48,0.00,C1755295439,510980.44,726678.19,0,0
1786247,162,CASH_OUT,360002.17,C147769232,40559.00,0.00,C1274160845,413342.48,773344.66,0,0
5599603,394,CASH_OUT,268638.60,C1240203788,315227.11,46588.51,C1401377152,0.00,268638.60,0,0
734431,38,CASH_OUT,147097.45,C685201914,19902.00,0.00,C526139069,122658.66,269756.11,0,0
2165257,184,PAYMENT,9103.46,C1309248882,87210.00,78106.54,M1878383571,0.00,0.00,0,0
5068356,354,PAYMENT,14981.55,C1938970945,83506.59,68525.04,M41199429,0.00,0.00,0,0
5518148,380,PAYMENT,4607.73,C1159872482,0.00,0.00,M121246574,0.00,0.00,0,0
783935,39,PAYMENT,209.87,C544687031,509.00,299.13,M539917317,0.00,0.00,0,0

In [53]:
dadosfinais = dadosfinais.sample(frac = 1)
dadosfinais = dadosfinais.reset_index()
dadosfinais.isFraud.value_counts(True)

0    0.752717
1    0.247283
Name: isFraud, dtype: float64

In [54]:
dadosfinais.columns

Index(['index', 'step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg',
       'newbalanceOrig', 'nameDest', 'oldbalanceDest', 'newbalanceDest',
       'isFraud', 'isFlaggedFraud'],
      dtype='object')

In [55]:
#utilizando o naive bayes retirado do site https://www.analyticsvidhya.com/blog/2017/09/naive-bayes-explained/
#utilizando a mesma base de dados utilizada para treinar o naive bayes.
dadosteste = dadosfinais[:5000]
dadostreinamento = dadosfinais[5000:]
y = dadostreinamento.isFraud
x = dadostreinamento.loc[:, [ 'step', 'amount', 'oldbalanceOrg',
       'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']]
z = dadosteste.loc[:, [ 'step', 'amount', 'oldbalanceOrg',
       'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']]
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x,y)
predicted = model.predict(z)
print(predicted)
#help(model.predict)

[0 0 0 ..., 0 0 0]

In [56]:
#comparando o real com a classficação do naive bayes
dadosteste['predicted'] = pd.Series(predicted)
dadosteste = dadosteste.loc[:, ["isFraud", "predicted"]]
print(dadosteste.isFraud.value_counts())

print(dadosteste.predicted.value_counts())

0    3744
1    1256
Name: isFraud, dtype: int64
0    4471
1     529
Name: predicted, dtype: int64

C:\Users\Luca\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

rodar o naive bayes qualitativo (multinomial) e fazer falsos positivos, verdadeiros positivos... (proj2)